name: diffusionmagic-env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.2.1
  - pytorch-cuda=11.7
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.19.2
  - pip:
      - accelerate==0.23.0
      - diffusers==0.21.1
      - gradio==3.39.0
      - safetensors==0.3.1
      - scipy==1.10.0
      - transformers==4.33.2
      - pydantic==1.10.4
      - mypy==1.0.0
      - black==23.1.0
      - flake8==6.0.0
      - markupsafe==2.1.3
      - opencv-contrib-python==4.7.0.72
      - controlnet-aux==0.0.1
      - invisible-watermark==0.2.0